error: Add JSON formatted errors for vacate APIs
Introduces a series of changes which allow the `allocator.Vacate()` to
return a multierror which can serialize the errors to JSON format.

To do so, multiple changes have been made throughout multiple packages,
providing building blocks for other APIs to leverage these, or use on-
demand.

`multierror.WithFormat()`: modifies a `multierror.Prefixed` or hashicorp
`multierror.Error` format functions which instead of formatting with a
"text" format, return a JSON formatted string.

`apierror.JSONError{}`: wrapping any `string` with this type, will make
it compatible to `json.Marshal`-ed. A `apierror.NewJSONError()` func is
provided for convenience too, allowing errors to be wrapped in the type.

`plan.StreamJSON`: has been fixed to return the final `error` result in
JSON formatted form.

`plan`: Legacy format has now been removed since it's no longer used.

`allocatorapi.VacateError`: now used for most of the returned vacate
errors since it supports both text and JSON formats.

Signed-off-by: Marc Lopez <marc5.12@outlook.com>